export const headers = [
  { _id: 1, key: "brandName", name: "Brand Name" },
  { _id: 2, key: "customerName", name: "Customer Name" },
  { _id: 3, key: "customerType", name: "Customer Type" },
  { _id: 4, key: "companyName", name: "Company Name" },
  {
    _id: 5,
    key: "serviceID",
    name: "Service ID",
  },
  { _id: 6, key: "radUserName", name: "User Name" },
  { _id: 7, key: "radPassword", name: "Password" },
  { _id: 8, key: "serviceIDName", name: "Service ID Name" },
  { _id: 9, key: "mode", name: "Mode" },
  { _id: 10, key: "staticIP", name: "Static IP" },
  { _id: 11, key: "serviceType", name: "Service Type" },
  { _id: 12, key: "plan", name: "Plan" },
  { _id: 13, key: "paymentCurrency", name: "Payment Currency" },
  { _id: 14, key: "price", name: "Price" },
  { _id: 15, key: "serviceStatus", name: "Service Status" },
  { _id: 16, key: "billingMethod", name: "Billing Method" },
  { _id: 17, key: "serviceStartDate", name: "Start Date" },
  { _id: 18, key: "serviceEndDate", name: "End Date" },
  { _id: 19, key: "duration", name: "Duration" },
  { _id: 20, key: "paymentTypes", name: "Payment Types" },
  { _id: 21, key: "city", name: "City" },
  { _id: 22, key: "township", name: "Township" },
  { _id: 23, key: "address", name: "Address" },
  { _id: 24, key: "coordinates", name: "Coordinates" },
  { _id: 25, key: "phoneNumber", name: "Phone Number" },
  { _id: 26, key: "viberNumber", name: "Viber Number" },
  { _id: 27, key: "email", name: "Email" },
  { _id: 27, key: "remark", name: "Remark" },
];

// export const body = [
//   {
//     _id: 1,
//     name: "kaung min khant",
//     age: 22,
//     city: "Yangon",
//     country: "Myanmar",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 2,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 3,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 4,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },

//   {
//     _id: 5,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 6,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 7,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },

//   {
//     _id: 8,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 9,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 10,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 11,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 12,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 13,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 14,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 15,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 16,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 17,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 18,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 19,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 20,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 21,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },

//   {
//     _id: 22,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 23,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 24,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 25,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 26,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 27,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 28,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 29,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 30,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 31,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 32,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 33,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 34,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 35,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },

//   {
//     _id: 36,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 37,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 38,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
//   {
//     _id: 39,
//     name: "min kaung khant",
//     age: 33,
//     city: "",
//     country: "",
//     village: "laydaungkan",
//     school: "BEHS.3.Dagon",
//     university: "Dagon University",
//     position: "Programmer",
//     lat: "1.1.1.1",
//     lng: "2.2.2.2",
//     package: "Sweet",
//     plan: "Sweet plan",
//     pppoe: "This is PPPOE",
//   },
// ];

export const body = [];
