export const headers = [
  { _id: 1, key: "name", name: "Name" },
  { _id: 2, key: "age", name: "Age" },
  { _id: 3, key: "city", name: "City" },
  { _id: 4, key: "country", name: "Country" },
  { _id: 5, key: "village", name: "Village" },
  { _id: 6, key: "school", name: "School" },
  { _id: 7, key: "university", name: "University" },
  { _id: 8, key: "position", name: "Position" },
  { _id: 9, key: "lat", name: "Latitude" },
  { _id: 10, key: "lng", name: "Longitude" },
  { _id: 11, key: "package", name: "Package" },
  { _id: 12, key: "plan", name: "Plan" },
  { _id: 13, key: "pppoe", name: "PPPoe" },
];

export const body = [
  {
    _id: 1,
    name: "kaung min khant",
    age: 22,
    city: "Yangon",
    country: "Myanmar",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 2,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 3,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 4,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },

  {
    _id: 5,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 6,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 7,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },

  {
    _id: 8,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 9,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 10,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 11,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 12,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 13,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 14,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 15,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 16,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 17,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 18,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 19,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 20,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 21,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },

  {
    _id: 22,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 23,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 24,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 25,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 26,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 27,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 28,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 29,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 30,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 31,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 32,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 33,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 34,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 35,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },

  {
    _id: 36,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 37,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 38,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
  {
    _id: 39,
    name: "min kaung khant",
    age: 33,
    city: "",
    country: "",
    village: "laydaungkan",
    school: "BEHS.3.Dagon",
    university: "Dagon University",
    position: "Programmer",
    lat: "1.1.1.1",
    lng: "2.2.2.2",
    package: "Sweet",
    plan: "Sweet plan",
    pppoe: "This is PPPOE",
  },
];
