import Mukta from "../../assets/fonts/Mukta-Regular.ttf";

import { SiGoogleearth } from "react-icons/si";
import { IoColorFilter } from "react-icons/io5";
import { DefaultThemeTypes } from "./_types";
import { HiColorSwatch } from "react-icons/hi";
import { IoColorFill } from "react-icons/io5";
import { IoIosColorPalette } from "react-icons/io";
import { BiSolidColor } from "react-icons/bi";

export const DEFAULT_THEMES: DefaultThemeTypes[] = [
  {
    id: 1,
    logo: <SiGoogleearth size={60} />,
    detailLogo: <SiGoogleearth size={60} />,
    name: "Default Theme",
    primaryColor: [
      "bg-default",
      "text-base_light",
      "bg-primary",
      "text-default",
      "laptop:hover:bg-primary",
      "laptop:hover:text-default",
      "laptop:hover:bg-default",
      "laptop:hover:text-primary",
      "border-primary_dark",
    ],
    secondaryColor: ["bg-slate-100", "text-base_light"],
    dashboardColor: [
      "bg-default_light",
      "text-black",
      "bg-primary_light",
      "text-default",
    ],
    navColor: [
      "bg-default",
      "text-black",
      "bg-primary",
      "text-default",
      "laptop:hover:bg-default_light",
      "hover:text-black",
    ],
    tableColor: [
      "odd:bg-default",
      "even:bg-default_light",
      "laptop:hover:bg-primary",
    ],
    inputColor: [
      "placeholder:text-slate-400",
      " text-base_light",
      "focus:border-primary",
      "focus:shadow-primary",
      "border:default_dark",
      "shadow-sm shadow-primary",
    ],
    textColor: ["text-base_light", "text-primary"],
    alertColor: [
      "bg-slate-100",
      "text-base_light",
      "border-slate-500 border-dashed",
      "bg-danger",
      "text-danger",
      "border-red-500 ",
    ],
    description: "Welcome to the default theme",
    font: Mukta,
    websiteLink: "www.google.com",
    generalColor: {
      primary: { bg: "bg-default", text: "text-black" },
      secondary: { bg: "bg-default_light", text: "text-black" },
    },
    statusColor: {
      success: { bg: "bg-success", text: "text-default" },
      danger: { bg: "bg-danger", text: "text-default" },
      disabled: { bg: "bg-default_dark", text: "text-default" },
    },
    actionColor: {
      createColor: { bg: "bg-success", text: "text-default" },
      updateColor: { bg: "bg-primary", text: "text-default" },
      deleteColor: { bg: "bg-danger", text: "text-default" },
    },
  },
  {
    id: 2,
    logo: <HiColorSwatch size={60} />,
    detailLogo: <HiColorSwatch size={60} />,
    name: "Color Theme",
    primaryColor: [
      "bg-primary",
      "text-default",
      "bg-primary_light",
      "text-primary",
      "laptop:hover:bg-default_light",
      "laptop:hover:text-primary",
      "laptop:hover:bg-primary",
      "laptop:hover:text-default_light",
      "border-default ",
    ],
    secondaryColor: ["bg-primary", "text-default"],
    dashboardColor: [
      "bg-primary_dark",
      "text-default_light",
      "bg-default",
      "text-black",
    ],
    navColor: [
      "bg-primary",
      "text-default ",
      "bg-default",
      "text-black",
      "laptop:hover:bg-default_light",
      "hover:text-black",
    ],
    tableColor: [
      "odd:bg-default_light",
      "even:bg-primary_light",
      "laptop:hover:bg-primary_dark",
    ],
    inputColor: [
      "placeholder:text-default_light",
      "text-default ",
      "focus:border-default_light",
      "focus:shadow-default_light",
      "border:default_light",
      "shadow shadow-default",
    ],
    textColor: ["text-default_light", "text-default"],
    alertColor: [
      "bg-[#2a2b3271]",
      "text-base_light",
      "border-slate-100 border-dashed",
      "bg-red-300",
      "text-yellow-300",
      "border-yellow-300",
    ],
    description: "Welcome to the default theme",
    font: Mukta,
    websiteLink: "www.google.com",
    generalColor: {
      primary: { bg: "bg-primary", text: "text-default" },
      secondary: { bg: "bg-default_light", text: "text-black" },
    },
    statusColor: {
      success: { bg: "bg-success", text: "text-default" },
      danger: { bg: "bg-danger", text: "text-default" },
      disabled: { bg: "bg-default_dark", text: "text-default" },
    },
    actionColor: {
      createColor: { bg: "bg-green-400", text: "text-default" },
      updateColor: { bg: "bg-primary_light", text: "text-black" },
      deleteColor: { bg: "bg-red-400", text: "text-default" },
    },
  },
  {
    id: 3,
    logo: <IoColorFill size={60} />,
    detailLogo: <IoColorFill size={60} />,
    name: "Clean Dark",
    primaryColor: [
      "bg-default",
      "text-base_light",
      "bg-[#2a2b32]",
      "text-default",
      "laptop:hover:bg-[#2a2b32]",
      "laptop:hover:text-default",
      "laptop:hover:bg-default",
      "laptop:hover:text-[#2a2b32]",
      "border-primary_dark",
    ],
    secondaryColor: ["bg-slate-100", "text-base_light"],
    dashboardColor: [
      "bg-default_light",
      "text-black",
      "bg-primary_light",
      "text-default",
    ],
    navColor: [
      "bg-default",
      "text-black",
      "bg-[#2a2b32]",
      "text-default",
      "laptop:hover:bg-default_light",
      "hover:text-black",
    ],
    tableColor: [
      "odd:bg-default",
      "even:bg-default_light",
      "laptop:hover:bg-[#2a2b32]",
    ],
    inputColor: [
      "placeholder:text-slate-400",
      " text-base_light",
      "focus:border-[#2a2b32]",
      "focus:shadow-[#2a2b32]",
      "border:default_dark",
      "shadow-sm shadow-[#2a2b32]",
    ],
    textColor: ["text-base_light", "text-[#2a2b32]"],
    alertColor: [
      "bg-slate-100",
      "text-base_light",
      "border-slate-500 border-dashed",
      "bg-danger",
      "text-danger",
      "border-red-500 ",
    ],
    description: "Welcome to the default theme",
    font: Mukta,
    websiteLink: "www.google.com",
    generalColor: {
      primary: { bg: "bg-default", text: "text-black" },
      secondary: { bg: "bg-default_light", text: "text-black" },
    },
    statusColor: {
      success: { bg: "bg-success", text: "text-default" },
      danger: { bg: "bg-danger", text: "text-default" },
      disabled: { bg: "bg-default_dark", text: "text-default" },
    },
    actionColor: {
      createColor: { bg: "bg-success", text: "text-default" },
      updateColor: { bg: "bg-[#2a2b32]", text: "text-default" },
      deleteColor: { bg: "bg-danger", text: "text-default" },
    },
  },
  {
    id: 4,
    logo: <IoColorFilter size={60} />,
    detailLogo: <IoColorFilter size={60} />,
    name: "Eye protection",
    primaryColor: [
      "bg-[#2a2b32]",
      "text-white",
      "bg-gray-700",
      "text-default_light",
      "laptop:hover:bg-default_light",
      "laptop:hover:text-base_light",
      "laptop:hover:bg-[#2a2b32]",
      "laptop:hover:text-default",
      "border-default ",
    ],
    secondaryColor: ["bg-gray-500", "text-default"],
    dashboardColor: [
      "bg-[#5C5858]",
      "text-default",
      "bg-default",
      "text-black",
    ],
    navColor: [
      "bg-[#2a2b32]",
      "text-default ",
      "bg-default",
      "text-black",
      "laptop:hover:bg-default_light",
      "hover:text-black",
    ],
    tableColor: [
      "odd:bg-default_light",
      "even:bg-default",
      "laptop:hover:bg-[#2a2b32]",
    ],
    inputColor: [
      "placeholder:text-default_light",
      "text-default ",
      "focus:border-default_light",
      "focus:shadow-default_light",
      "border:default_light",
      "shadow shadow-default",
    ],
    textColor: ["text-default_light", "text-default"],
    alertColor: [
      "bg-[#37383f]",
      "text-base_light",
      "border-slate-100 border-dashed",
      "bg-red-500",
      "text-red-300",
      "border-red-300",
    ],
    description: "Welcome to the default theme",
    font: Mukta,
    websiteLink: "www.google.com",
    generalColor: {
      primary: { bg: "bg-[#2a2b32]", text: "text-default" },
      secondary: { bg: "bg-default_light", text: "text-black" },
    },
    statusColor: {
      success: { bg: "bg-success", text: "text-default" },
      danger: { bg: "bg-danger", text: "text-default" },
      disabled: { bg: "bg-default_dark", text: "text-default" },
    },
    actionColor: {
      createColor: { bg: "bg-green-400", text: "text-default" },
      updateColor: { bg: "bg-primary_light", text: "text-black" },
      deleteColor: { bg: "bg-red-400", text: "text-default" },
    },
  },
  {
    id: 5,
    logo: <BiSolidColor size={60} />,
    detailLogo: <BiSolidColor size={60} />,
    name: "School Theme",
    primaryColor: [
      "bg-default",
      "text-base_light",
      "bg-[#317873]",
      "text-default",
      "laptop:hover:bg-[#317873]",
      "laptop:hover:text-default",
      "laptop:hover:bg-default",
      "laptop:hover:text-[#317873]",
      "border-primary_dark",
    ],
    secondaryColor: ["bg-slate-100", "text-base_light"],
    dashboardColor: [
      "bg-default_light",
      "text-black",
      "bg-primary_light",
      "text-default",
    ],
    navColor: [
      "bg-default",
      "text-black",
      "bg-[#317873]",
      "text-default",
      "laptop:hover:bg-default_light",
      "hover:text-black",
    ],
    tableColor: [
      "odd:bg-default",
      "even:bg-default_light",
      "laptop:hover:bg-[#317873]",
    ],
    inputColor: [
      "placeholder:text-slate-400",
      " text-base_light",
      "focus:border-[#317873]",
      "focus:shadow-[#317873]",
      "border:default_dark",
      "shadow-sm shadow-[#317873]",
    ],
    textColor: ["text-base_light", "text-[#317873]"],
    alertColor: [
      "bg-slate-100",
      "text-base_light",
      "border-slate-500 border-dashed",
      "bg-danger",
      "text-danger",
      "border-red-500 ",
    ],
    description: "Welcome to the default theme",
    font: Mukta,
    websiteLink: "www.google.com",
    generalColor: {
      primary: { bg: "bg-default", text: "text-black" },
      secondary: { bg: "bg-default_light", text: "text-black" },
    },
    statusColor: {
      success: { bg: "bg-success", text: "text-default" },
      danger: { bg: "bg-danger", text: "text-default" },
      disabled: { bg: "bg-default_dark", text: "text-default" },
    },
    actionColor: {
      createColor: { bg: "bg-success", text: "text-default" },
      updateColor: { bg: "bg-[#317873]", text: "text-default" },
      deleteColor: { bg: "bg-danger", text: "text-default" },
    },
  },
  {
    id: 6,
    logo: <IoIosColorPalette size={60} />,
    detailLogo: <IoColorFilter size={60} />,
    name: "Golden Green",
    primaryColor: [
      "bg-[#317873]",
      "text-white",
      "bg-[#af8b2e]",
      "text-default",
      "laptop:hover:bg-default_light",
      "laptop:hover:text-base_light",
      "laptop:hover:bg-[#317873]",
      "laptop:hover:text-default",
      "border-default ",
    ],
    secondaryColor: ["bg-gray-500", "text-default"],
    dashboardColor: [
      "bg-[#599786]",
      "text-default",
      "bg-default",
      "text-black",
    ],
    navColor: [
      "bg-[#317873]",
      "text-default ",
      "bg-default",
      "text-black",
      "laptop:hover:bg-default_light",
      "hover:text-black",
    ],
    tableColor: [
      "odd:bg-default_light",
      "even:bg-default",
      "laptop:hover:bg-[#317873]",
    ],
    inputColor: [
      "placeholder:text-default_light",
      "text-default ",
      "focus:border-default_light",
      "focus:shadow-default_light",
      "border:default_light",
      "shadow shadow-default",
    ],
    textColor: ["text-default_light", "text-default"],
    alertColor: [
      "bg-[#205753] ",
      "text-base_light",
      "border-slate-100 border-dashed",
      "bg-red-500",
      "text-red-300",
      "border-red-300",
    ],
    description: "Welcome to the default theme",
    font: Mukta,
    websiteLink: "www.google.com",
    generalColor: {
      primary: { bg: "bg-[#317873]", text: "text-default" },
      secondary: { bg: "bg-default_light", text: "text-black" },
    },
    statusColor: {
      success: { bg: "bg-success", text: "text-default" },
      danger: { bg: "bg-danger", text: "text-default" },
      disabled: { bg: "bg-default_dark", text: "text-default" },
    },
    actionColor: {
      createColor: { bg: "bg-green-400", text: "text-default" },
      updateColor: { bg: "bg-primary_light", text: "text-black" },
      deleteColor: { bg: "bg-red-400", text: "text-default" },
    },
  },
];
