import { createRef } from "react";
import {
  DataCenterTypes,
  ErrorCenterTypes,
  RefCenterTypes,
  SelectInputTypes,
} from "./_types";
import { TabType } from "../../Components/Menus/TabMenu/_types";
import { inputAcceptableDate } from "../../Utils/Date/date.utils";

const date = new Date();

export const DEFAULT_DATA_CENTER: DataCenterTypes = {
  brandName: "",
  customerName: "",
  customerType: "Individual",
  customerTypeServer: "individual",
  companyName: "",
  autoGeneratePPOEAccount: "On",
  autoGeneratePPOEAccountServer: true,
  radUserName: "",
  radPassword: "",
  serviceID: "",
  serviceIDName: "",
  containIP: "OFF",
  containIPServer: false,
  mode: "",
  modeServer: "",
  staticIP: "",
  serviceType: "",
  serviceTypeServer: "",
  plan: "",
  planServer: "",
  paymentCurrency: "",
  price: "0",
  billingMethod: "Prepaid",
  billingMethodServer: "pre",
  serviceStatus: "New",
  serviceStartDate: inputAcceptableDate(date),
  serviceEndDate: "",
  duration: "hours",
  durationNumber: "",
  enable: "Off",
  enableServer: false,
  paymentTypes: "",
  mmk: "",
  sgd: "",
  baht: "",
  city: "",
  township: "",
  address: "",
  coordinates: "",
  phoneNumber: "",
  viberNumber: "",
  email: "",
  remark: "",
};

export const DEFAULT_ERROR_CENTER: ErrorCenterTypes = {
  brandName: "",
  customerName: "",
  customerType: "",
  customerTypeServer: "",
  companyName: "",
  autoGeneratePPOEAccount: "",
  autoGeneratePPOEAccountServer: "",
  radUserName: "",
  radPassword: "",
  serviceID: "",
  serviceIDName: "",
  containIP: "",
  containIPServer: "",
  mode: "",
  modeServer: "",
  staticIP: "",
  serviceType: "",
  serviceTypeServer: "",
  plan: "",
  planServer: "",
  paymentCurrency: "",
  price: "",
  billingMethod: "",
  billingMethodServer: "",
  serviceStatus: "",
  serviceStartDate: "",
  serviceEndDate: "",
  duration: "",
  durationNumber: "",
  enable: "",
  enableServer: "",
  paymentTypes: "",
  mmk: "",
  sgd: "",
  baht: "",
  city: "",
  township: "",
  address: "",
  coordinates: "",
  phoneNumber: "",
  viberNumber: "",
  email: "",
  remark: "",
};

export const DEFAULT_REF_CENTER: RefCenterTypes = {
  brandName: createRef(),
  customerName: createRef(),
  customerType: createRef(),
  companyName: createRef(),
  autoGeneratePPOEAccount: createRef(),
  radUserName: createRef(),
  radPassword: createRef(),
  serviceID: createRef(),
  serviceIDName: createRef(),
  containIP: createRef(),
  mode: createRef(),
  staticIP: createRef(),
  serviceType: createRef(),
  plan: createRef(),
  paymentCurrency: createRef(),
  price: createRef(),
  billingMethod: createRef(),
  serviceStatus: createRef(),
  serviceStartDate: createRef(),
  serviceEndDate: createRef(),
  duration: createRef(),
  durationNumber: createRef(),
  paymentTypes: createRef(),
  mmk: createRef(),
  sgd: createRef(),
  baht: createRef(),
  city: createRef(),
  township: createRef(),
  address: createRef(),
  coordinates: createRef(),
  phoneNumber: createRef(),
  viberNumber: createRef(),
  email: createRef(),
  remark: createRef(),
};

export const DEFAULT_SELECT_INPUT_CENTER: SelectInputTypes = {
  paymentTypes: [],
};

export const TABS: TabType[] = [
  { id: 1, name: "General" },
  { id: 2, name: "Network" },
  { id: 3, name: "Billing" },
];

export const GENERAL_ID = 1;
export const NETWORK_AND_BILLING_ID = 2;
export const BILLING_CONTACT_INFORMATION_ID = 3;
