export type DataCenterTypes = {
  brandName: string;
  customerName: string;
  customerType: string;
  customerTypeServer: string;
  companyName: string;
  autoGeneratePPOEAccount: string;
  autoGeneratePPOEAccountServer: boolean | string;
  radUserName: string;
  radPassword: string;
  serviceID: string;
  serviceIDName: string;
  containIP: string;
  containIPServer: boolean | string;
  mode: string;
  modeServer: string;
  staticIP: string;
  serviceType: string;
  serviceTypeServer: string;
  plan: string;
  planServer: string;
  paymentCurrency: string;
  price: string;
  billingMethod: string;
  billingMethodServer: string;
  serviceStatus: string;
  serviceStartDate: string;
  serviceEndDate: string;
  duration: string;
  durationNumber: string;
  memberID: string;
  cities: string;
  townships: string;
  address: string;
  coordinates: string;
  phoneNumber: string;
  email: string;
  viberNumber: string;
  remark: string;
  enable: string;
  enableServer: boolean | string;
};

export type ErrorCenterTypes = {
  brandName: string;
  customerName: string;
  customerType: string;
  customerTypeServer: string;
  companyName: string;
  autoGeneratePPOEAccount: string;
  autoGeneratePPOEAccountServer: boolean | string;
  radUserName: string;
  radPassword: string;
  serviceID: string;
  serviceIDName: string;
  containIP: string;
  containIPServer: boolean | string;
  mode: string;
  modeServer: string;
  staticIP: string;
  serviceType: string;
  serviceTypeServer: string;
  plan: string;
  planServer: string;
  paymentCurrency: string;
  price: string;
  billingMethod: string;
  billingMethodServer: string;
  serviceStatus: string;
  serviceStartDate: string;
  serviceEndDate: string;
  duration: string;
  durationNumber: string;
  memberID: string;
  cities: string;
  townships: string;
  address: string;
  coordinates: string;
  phoneNumber: string;
  email: string;
  viberNumber: string;
  remark: string;
  enable: string;
  enableServer: boolean | string;
};

export type RefCenterTypes = {
  brandName: RefObject;
  customerName: RefObject;
  customerType: RefObject;
  companyName: RefObject;
  autoGeneratePPOEAccount: RefObject;
  radUserName: RefObject;
  radPassword: RefObject;
  serviceID: RefObject;
  serviceIDName: RefObject;
  containIP: RefObject;
  mode: RefObject;
  staticIP: RefObject;
  serviceType: RefObject;
  plan: RefObject;
  paymentCurrency: RefObject;
  price: RefObject;
  billingMethod: RefObject;
  serviceStatus: RefObject;
  serviceStartDate: RefObject;
  serviceEndDate: RefObject;
  duration: RefObject;
  durationNumber: RefObject;
  memberID: RefObject;
  cities: RefObject;
  townships: RefObject;
  address: RefObject;
  coordinates: RefObject;
  phoneNumber: RefObject;
  email: RefObject;
  viberNumber: RefObject;
  remark: RefObject;
  enable: RefObject;
};
