import { createRef } from "react";
import { DataCenterTypes, ErrorCenterTypes, RefCenterTypes } from "./_types";
import { TabType } from "../../../Components/Menus/TabMenu/_types";

export const DEFAULT_DATA_CENTER: DataCenterTypes = {
  brandName: "",
  customerName: "",
  customerType: "Individual",
  customerTypeServer: "individual",
  companyName: "",
  autoGeneratePPOEAccount: "OFF",
  autoGeneratePPOEAccountServer: false,
  radUserName: "",
  radPassword: "",
  serviceID: "",
  serviceIDName: "",
  containIP: "OFF",
  containIPServer: false,
  mode: "",
  modeServer: "",
  staticIP: "",
  serviceType: "",
  serviceTypeServer: "",
  plan: "",
  planServer: "",
  paymentCurrency: "",
  price: "0",
  billingMethod: "Prepaid",
  billingMethodServer: "pre",
  serviceStatus: "New",
  serviceStartDate: "",
  serviceEndDate: "",
  duration: "hours",
  durationNumber: "",
  memberID: "",
  cities: "",
  townships: "",
  address: "",
  coordinates: "",
  phoneNumber: "",
  email: "",
  viberNumber: "",
  remark: "",
  enable: "OFF",
  enableServer: false,
};

export const DEFAULT_ERROR_CENTER: ErrorCenterTypes = {
  brandName: "",
  customerName: "",
  customerType: "",
  customerTypeServer: "",
  companyName: "",
  autoGeneratePPOEAccount: "",
  autoGeneratePPOEAccountServer: "",
  radUserName: "",
  radPassword: "",
  serviceID: "",
  serviceIDName: "",
  containIP: "",
  containIPServer: "",
  mode: "",
  modeServer: "",
  staticIP: "",
  serviceType: "",
  serviceTypeServer: "",
  plan: "",
  planServer: "",
  paymentCurrency: "",
  price: "",
  billingMethod: "",
  billingMethodServer: "",
  serviceStatus: "",
  serviceStartDate: "",
  serviceEndDate: "",
  duration: "",
  durationNumber: "",
  memberID: "",
  cities: "",
  townships: "",
  address: "",
  coordinates: "",
  phoneNumber: "",
  email: "",
  viberNumber: "",
  remark: "",
  enable: "",
  enableServer: "",
};

export const DEFAULT_REF_CENTER: RefCenterTypes = {
  brandName: createRef(),
  customerName: createRef(),
  customerType: createRef(),
  companyName: createRef(),
  autoGeneratePPOEAccount: createRef(),
  radUserName: createRef(),
  radPassword: createRef(),
  serviceID: createRef(),
  serviceIDName: createRef(),
  containIP: createRef(),
  mode: createRef(),
  staticIP: createRef(),
  serviceType: createRef(),
  plan: createRef(),
  paymentCurrency: createRef(),
  price: createRef(),
  billingMethod: createRef(),
  serviceStatus: createRef(),
  serviceStartDate: createRef(),
  serviceEndDate: createRef(),
  duration: createRef(),
  durationNumber: createRef(),
  memberID: createRef(),
  cities: createRef(),
  townships: createRef(),
  address: createRef(),
  coordinates: createRef(),
  phoneNumber: createRef(),
  email: createRef(),
  viberNumber: createRef(),
  remark: createRef(),
  enable: createRef(),
};

export const TABS: TabType[] = [
  { id: 1, name: "General" },
  { id: 2, name: "Network And Billing" },
  { id: 3, name: "Billing Contact Information" },
];

export const GENERAL_ID = 1;
export const NETWORK_AND_BILLING_ID = 2;
export const BILLING_CONTACT_INFORMATION_ID = 3;
