export const PACKAGES = [
  { id: 1, label: "Basic Internet Plan" },
  { id: 2, label: "Unlimited Streaming Plan" },
  { id: 3, label: "Standard Plan" },
  { id: 4, label: "Premium Plan" },
  { id: 5, label: "Family Bundle" },
  { id: 6, label: "Student Special" },
  { id: 7, label: "Business Pro" },
  { id: 8, label: "Corporate Plan" },
  { id: 9, label: "Economy Plan" },
  { id: 10, label: "Essential Plan" },
  { id: 11, label: "Traveler's Pack" },
  { id: 12, label: "Weekend Plan" },
  { id: 13, label: "Home Internet" },
  { id: 14, label: "Office Internet" },
  { id: 15, label: "Ultra Fast Package" },
  { id: 16, label: "Turbo Plan" },
  { id: 17, label: "Sports Streaming Package" },
  { id: 18, label: "Gaming Pro" },
  { id: 19, label: "Movie Lover's Pack" },
  { id: 20, label: "Music Streaming Plan" },
  { id: 21, label: "News & Updates Plan" },
  { id: 22, label: "Remote Work Plan" },
  { id: 23, label: "Zoom Meeting Package" },
  { id: 24, label: "Social Media Plan" },
  { id: 25, label: "Work From Home Package" },
  { id: 26, label: "Gigabit Internet" },
  { id: 27, label: "Mobile Hotspot Plan" },
  { id: 28, label: "Cloud Backup Plan" },
  { id: 29, label: "High-Speed Internet" },
  { id: 30, label: "Small Business Plan" },
  { id: 31, label: "International Data Package" },
  { id: 32, label: "Family Streaming Bundle" },
];
