import { CustomerValidationTypes } from "./_types";

export const DEFAULT_CUSTOMER_VALIDATIONS: CustomerValidationTypes = {
  brandName: "Select brand name",
  customerName: "Enter customer name",
  customerType: "Select customer type",
  autoGeneratePPOEAccount: "Select PPPOE account",
  radUserName: "Enter Rad user name ",
  radPassword: "Enter Rad password",
  serviceID: "Select service ID",
  serviceIDName: "Enter service ID name",
  containIP: "Select Contain IP",
  mode: "Select mode",
  staticIP: "Enter static ip",
  serviceType: "Select service type",
  plan: "Select plan",
  paymentCurrency: "Select payment currency",
  price: "Enter price",
  billingMethod: "Select billing method",
  serviceStatus: "Enter service status",
  serviceStartDate: "Enter start date",
  serviceEndDate: "Enter end date",
  duration: "Select duration",
  durationNumber: "Enter duration number",
  paymentTypes: "Select payment types",
  mmk: "Enter MMK amount",
  sgd: "Enter SGD amunt",
  baht: "Enter BAHT amount",
  city: "Select city",
  township: "Select township",
  address: "Enter address",
  coordinates: "Enter coordinates",
  phoneNumber: "Enter phone number",
  email: "Enter email",
  viberNumber: "Enter viber number",
  remark: "Enter remark",
};
